/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: test@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUser200Response
 */
export interface CreateUser200Response {
    /**
     * 
     * @type {string}
     * @memberof CreateUser200Response
     */
    message: string;
}

/**
 * Check if a given object implements the CreateUser200Response interface.
 */
export function instanceOfCreateUser200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function CreateUser200ResponseFromJSON(json: any): CreateUser200Response {
    return CreateUser200ResponseFromJSONTyped(json, false);
}

export function CreateUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUser200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function CreateUser200ResponseToJSON(value?: CreateUser200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

